# Generated by Django 4.2 on 2023-06-22 07:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aktyor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=30)),
                ('sharif', models.CharField(max_length=30)),
                ('davlat', models.CharField(choices=[('Uzbekistan', 'Uzbekistan'), ('Russia', 'Russia'), ('Armenia', 'Armenia'), ('Tajikistan', 'Tajikistan'), ('Kazakhstan', 'Kazakhstan'), ('Kyrgzstan', 'Kyrgzstan'), ('Azerbayjan', 'Azerbayjan'), ('Moldova', 'Moldova'), ('Latviya', 'Latviya'), ('Turkmenistan', 'Turkmenistan')], max_length=50)),
                ('tugilgan_yil', models.DateField()),
                ('jins', models.CharField(choices=[('Erkak', 'Erkak'), ('Ayol', 'Ayol')], max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Kino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('janr', models.CharField(max_length=40)),
                ('yil', models.DateField()),
                ('davomiylik', models.DurationField()),
                ('reyting', models.FloatField(default=0)),
                ('aktyorlar', models.ManyToManyField(to='asosiy.aktyor')),
            ],
        ),
        migrations.CreateModel(
            name='Izoh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matn', models.CharField(blank=True, max_length=150, null=True)),
                ('sana', models.DateField(auto_now=True)),
                ('baho', models.FloatField()),
                ('kino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asosiy.kino')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
